services:
    mc:
        image: itzg/minecraft-server
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "25565:25565"
        volumes:
            - ./data:/data

        environment:
            # Java Settings
            MEMORY: 16G
            JVM_OPTS: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true --add-modules=jdk.incubator.vector"
            JVM_XX_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"

            # Server Settings
            TYPE: FABRIC
            EULA: true
            MOTD: "ยง5\u2764\u2764\u2764"
            ICON: "https://upload.wikimedia.org/wikipedia/commons/2/25/Pi%27erre_Bourne_-_The_Life_of_Pi%27erre_4.png"
            ENABLE_AUTOPAUSE: true

            # Gameplay Settings
            DIFFICULTY: hard
            MAX_PLAYERS: 16
            ENABLE_COMMAND_BLOCK: true
            SNOOPER_ENABLED: false
            SPAWN_PROTECTION: 0
            PLAYER_IDLE_TIMEOUT: 15
            VIEW_DISTANCE: 12
            SIMULATION_DISTANCE: 8
            MAX_TICK_TIME: -1
            ENABLE_WHITELIST: true
            ENFORCE_SECURE_PROFILE: false
            SYNC_CHUNK_WRITES: false
            MAX_CHAINED_NEIGHBOR_UPDATES: 10000

            # Addons
            INITIAL_ENABLED_PACKS: "bundle"
            REMOVE_OLD_MODS: true
            MODRINTH_ALLOWED_VERSION_TYPE: alpha
            MODRINTH_PROJECTS: |
                fabric-api
                no-chat-reports
                spark
                ledger
                modernfix
                ferrite-core
                lithium
                vmp-fabric
                c2me-fabric
                krypton
                noisium
