services:
    mc:
        image: itzg/minecraft-server
        restart: always
        ports:
            - "25565:25565"
        stdin_open: true
        tty: true
        environment:
            MEMORY: 16G
            JVM_OPTS: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
            JVM_XX_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"

            TYPE: PAPER
            EULA: "true"
            MOTD: "chems"
            DIFFICULTY: hard
            MAX_PLAYERS: 24
            ENABLE_COMMAND_BLOCK: true
            SNOOPER_ENABLED: false
            SPAWN_PROTECTION: 0
            VIEW_DISTANCE: 12
            SIMULATION_DISTANCE: 8
            MAX_TICK_TIME: -1
            ENFORCE_SECURE_PROFILE: false
            PLUGINS: |
              https://github.com/KaspianDev/AntiPopup/releases/download/b7a08d9/AntiPopup-9.2.jar
              https://github.com/kernitus/BukkitOldCombatMechanics/releases/latest/download/OldCombatMechanics.jar
              https://github.com/jadc/ElytraFlight/releases/download/1.1/elytraflight-1.1.jar
              https://cdn.modrinth.com/data/Lu3KuzdV/versions/llmrc4cl/CoreProtect-22.4.jar

            ENABLE_AUTOPAUSE: true

        volumes:
            - ./data:/data
