services:
    mc:
        image: itzg/minecraft-server
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "25565:25565"
        volumes:
            - ./data:/data

        environment:
            # Java Settings
            MEMORY: 16G
            JVM_OPTS: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true --add-modules=jdk.incubator.vector"
            JVM_XX_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"

            # Server Settings
            TYPE: PURPUR
            VERSION: LATEST
            EULA: true
            MOTD: "ยง4chems event"
            ICON: "https://upload.wikimedia.org/wikipedia/en/6/6c/Playboi_Carti_-_Whole_Lotta_Red.png"
            ENABLE_AUTOPAUSE: true
            USE_SIMD_FLAGS: true

            # Gameplay Settings
            DIFFICULTY: normal
            MAX_PLAYERS: 64
            VIEW_DISTANCE: 16
            SIMULATION_DISTANCE: 8

            ENABLE_COMMAND_BLOCK: true
            SNOOPER_ENABLED: false
            SPAWN_PROTECTION: 0
            PLAYER_IDLE_TIMEOUT: 15
            MAX_TICK_TIME: -1
            ENFORCE_SECURE_PROFILE: false
            SYNC_CHUNK_WRITES: false
            MAX_CHAINED_NEIGHBOR_UPDATES: 10000
            PATCH_DEFINITIONS: patches

            # Addons
            MODRINTH_ALLOWED_VERSION_TYPE: alpha
            #MODRINTH_PROJECTS: |
            PLUGINS: |
                https://github.com/KaspianDev/AntiPopup/releases/download/b7a08d9/AntiPopup-9.2.jar
                https://github.com/kernitus/BukkitOldCombatMechanics/releases/latest/download/OldCombatMechanics.jar
