services:
    mc:
        image: itzg/minecraft-server
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "25565:25565"
        volumes:
            - ./data:/data

        environment:
            TYPE: PURPUR
            VERSION: LATEST
            EULA: true
